#spring:
#  datasource:
#    url: jdbc:mysql://localhost/customrepo
#    username: root
#    password: toor
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#   show-sql: true
#    hibernate:
#      ddl-auto: create-drop
    #hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
    
      
