CREATE TABLE `test_entity` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(45) CHARACTER SET latin1 NOT NULL,
  `LAST_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

